# Generated by Django 4.2.7 on 2025-11-18 06:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        help_text="Patient age in years",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        help_text="Patient gender",
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "medical_history",
                    models.TextField(
                        blank=True,
                        help_text="Previous medical conditions, allergies, chronic diseases",
                    ),
                ),
                (
                    "current_medications",
                    models.TextField(
                        blank=True, help_text="Current medications and dosages"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact name and number",
                        max_length=100,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Linked user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="XRayImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        help_text="Original uploaded X-ray image",
                        upload_to="xrays/original/%Y/%m/%d/",
                    ),
                ),
                (
                    "processed_image",
                    models.ImageField(
                        blank=True,
                        help_text="CLAHE-enhanced image for AI analysis",
                        null=True,
                        upload_to="xrays/processed/%Y/%m/%d/",
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Clinical notes or observations"
                    ),
                ),
                ("image_width", models.IntegerField(blank=True, null=True)),
                ("image_height", models.IntegerField(blank=True, null=True)),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient this X-ray belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xrays",
                        to="detection.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="Doctor/staff who uploaded the image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_xrays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "X-Ray Image",
                "verbose_name_plural": "X-Ray Images",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("doctor", "Doctor/Staff"),
                            ("patient", "Patient"),
                        ],
                        default="patient",
                        help_text="User role for access control",
                        max_length=20,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Linked Django user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crossvit_prediction",
                    models.CharField(
                        help_text="CrossViT model prediction", max_length=50
                    ),
                ),
                (
                    "crossvit_confidence",
                    models.FloatField(
                        help_text="CrossViT confidence percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("resnet50_prediction", models.CharField(max_length=50)),
                (
                    "resnet50_confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("densenet121_prediction", models.CharField(max_length=50)),
                (
                    "densenet121_confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("efficientnet_prediction", models.CharField(max_length=50)),
                (
                    "efficientnet_confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("vit_prediction", models.CharField(max_length=50)),
                (
                    "vit_confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("swin_prediction", models.CharField(max_length=50)),
                (
                    "swin_confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "final_diagnosis",
                    models.CharField(
                        choices=[
                            ("COVID", "COVID-19"),
                            ("Normal", "Normal"),
                            ("Viral Pneumonia", "Viral Pneumonia"),
                            ("Lung Opacity", "Lung Opacity"),
                        ],
                        help_text="Final consensus diagnosis",
                        max_length=50,
                    ),
                ),
                (
                    "consensus_confidence",
                    models.FloatField(
                        help_text="Confidence of final diagnosis (average or weighted)"
                    ),
                ),
                (
                    "gradcam_heatmap",
                    models.ImageField(
                        blank=True,
                        help_text="Grad-CAM visualization showing important regions",
                        null=True,
                        upload_to="heatmaps/%Y/%m/%d/",
                    ),
                ),
                (
                    "large_branch_attention",
                    models.ImageField(
                        blank=True,
                        help_text="CrossViT large branch attention map",
                        null=True,
                        upload_to="attention/large/%Y/%m/%d/",
                    ),
                ),
                (
                    "small_branch_attention",
                    models.ImageField(
                        blank=True,
                        help_text="CrossViT small branch attention map",
                        null=True,
                        upload_to="attention/small/%Y/%m/%d/",
                    ),
                ),
                (
                    "inference_time",
                    models.FloatField(
                        help_text="Total inference time for all models (seconds)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor_notes",
                    models.TextField(
                        blank=True, help_text="Doctor's clinical assessment and notes"
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False,
                        help_text="Has this prediction been validated by a doctor?",
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Doctor who reviewed this prediction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "xray",
                    models.ForeignKey(
                        help_text="X-ray image being analyzed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="detection.xrayimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prediction",
                "verbose_name_plural": "Predictions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="detection_p_created_49528e_idx"
                    ),
                    models.Index(
                        fields=["final_diagnosis"],
                        name="detection_p_final_d_3699d0_idx",
                    ),
                ],
            },
        ),
    ]
