# Generated by Django 4.2.7 on 2025-11-18 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchUploadJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partially Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_images", models.IntegerField(default=0)),
                ("images_processed", models.IntegerField(default=0)),
                ("images_successful", models.IntegerField(default=0)),
                ("images_failed", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "apply_clahe",
                    models.BooleanField(
                        default=True, help_text="Apply CLAHE preprocessing"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Batch upload notes")),
                (
                    "error_log",
                    models.TextField(
                        blank=True, help_text="Errors encountered during processing"
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_upload_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient for all X-rays in this batch",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_jobs",
                        to="detection.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Upload Job",
                "verbose_name_plural": "Batch Upload Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BatchUploadImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file", models.ImageField(upload_to="xrays/batch/%Y/%m/%d/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(help_text="Processing order within batch"),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="detection.batchuploadjob",
                    ),
                ),
                (
                    "xray_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_upload_source",
                        to="detection.xrayimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Upload Image",
                "verbose_name_plural": "Batch Upload Images",
                "ordering": ["batch_job", "order"],
            },
        ),
        migrations.AddIndex(
            model_name="batchuploadjob",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="detection_b_created_e0fd96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="batchuploadjob",
            index=models.Index(
                fields=["status", "-created_at"], name="detection_b_status_8aeaf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batchuploadimage",
            index=models.Index(
                fields=["batch_job", "status"], name="detection_b_batch_j_3b1f1a_idx"
            ),
        ),
    ]
