# Generated by Django 4.2.7 on 2025-11-20 03:45

from django.db import migrations


def rename_doctor_to_staff(apps, schema_editor):
    """
    Rename all UserProfile records with role='doctor' to role='staff'
    """
    UserProfile = apps.get_model('detection', 'UserProfile')
    updated_count = UserProfile.objects.filter(role='doctor').update(role='staff')
    if updated_count > 0:
        print(f"Updated {updated_count} user profile(s) from 'doctor' to 'staff' role")


def rename_staff_to_doctor(apps, schema_editor):
    """
    Reverse migration: Rename all UserProfile records with role='staff' back to role='doctor'
    """
    UserProfile = apps.get_model('detection', 'UserProfile')
    updated_count = UserProfile.objects.filter(role='staff').update(role='doctor')
    if updated_count > 0:
        print(f"Reverted {updated_count} user profile(s) from 'staff' back to 'doctor' role")


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rename_doctor_to_staff, reverse_code=rename_staff_to_doctor),
    ]
