# Generated by Django 4.2.7 on 2025-11-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_rename_doctor_to_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff'), ('patient', 'Patient')], default='patient', help_text='User role for access control', max_length=20),
        ),
    ]
