# Generated by Django 4.2.7 on 2025-11-25 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='dashboardpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
    ]
