# Generated by Django 5.2.8 on 2025-11-18 12:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("detection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allergen", models.CharField(max_length=200)),
                (
                    "allergy_type",
                    models.CharField(
                        choices=[
                            ("medication", "Medication"),
                            ("food", "Food"),
                            ("environmental", "Environmental"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe/Anaphylaxis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reaction_description", models.TextField()),
                ("onset_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("verified_by_doctor", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="detection.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Allergies",
                "ordering": ["-severity", "allergen"],
            },
        ),
        migrations.CreateModel(
            name="COVIDRiskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("age_score", models.IntegerField(default=0)),
                ("comorbidity_score", models.IntegerField(default=0)),
                ("lifestyle_score", models.IntegerField(default=0)),
                ("vaccination_score", models.IntegerField(default=0)),
                ("total_score", models.IntegerField()),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("moderate", "Moderate Risk"),
                            ("high", "High Risk"),
                            ("very_high", "Very High Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(help_text="Detailed breakdown of risk factors"),
                ),
                ("recommendations", models.TextField()),
                (
                    "calculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_scores",
                        to="detection.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at"],
            },
        ),
        migrations.CreateModel(
            name="FamilyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("sibling", "Sibling"),
                            ("grandparent", "Grandparent"),
                            ("child", "Child"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition", models.CharField(max_length=200)),
                ("age_at_diagnosis", models.IntegerField(blank=True, null=True)),
                ("is_deceased", models.BooleanField(default=False)),
                ("cause_of_death", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_history",
                        to="detection.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Family Histories",
            },
        ),
        migrations.CreateModel(
            name="LifestyleInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smoking_status",
                    models.CharField(
                        choices=[
                            ("never", "Never Smoked"),
                            ("former", "Former Smoker"),
                            ("current", "Current Smoker"),
                        ],
                        default="never",
                        max_length=20,
                    ),
                ),
                ("cigarettes_per_day", models.IntegerField(blank=True, null=True)),
                ("years_smoked", models.IntegerField(blank=True, null=True)),
                ("quit_date", models.DateField(blank=True, null=True)),
                (
                    "alcohol_use",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("occasional", "Occasional"),
                            ("moderate", "Moderate"),
                            ("heavy", "Heavy"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("drinks_per_week", models.IntegerField(blank=True, null=True)),
                (
                    "exercise_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Light Activity"),
                            ("moderate", "Moderate Activity"),
                            ("active", "Very Active"),
                        ],
                        default="sedentary",
                        max_length=20,
                    ),
                ),
                (
                    "exercise_hours_per_week",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=200)),
                (
                    "occupational_exposure_risk",
                    models.BooleanField(
                        default=False,
                        help_text="High risk of COVID-19 exposure at work",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifestyle_info",
                        to="detection.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition_name", models.CharField(max_length=200)),
                (
                    "icd_code",
                    models.CharField(
                        blank=True, help_text="ICD-10 code", max_length=20
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                        ],
                        default="mild",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("chronic", "Chronic"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("diagnosed_date", models.DateField()),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("symptoms", models.TextField(blank=True)),
                ("treatment", models.TextField(blank=True)),
                (
                    "increases_covid_risk",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this condition increases COVID-19 risk",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diagnosed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnosed_conditions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_conditions",
                        to="detection.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-diagnosed_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("lab_result", "Lab Result"),
                            ("prescription", "Prescription"),
                            ("discharge_summary", "Discharge Summary"),
                            ("radiology", "Radiology Report"),
                            ("vaccination_cert", "Vaccination Certificate"),
                            ("insurance", "Insurance Document"),
                            ("consent_form", "Consent Form"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="medical_records/documents/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                ("file_size", models.IntegerField(blank=True, null=True)),
                (
                    "document_date",
                    models.DateField(
                        help_text="Date of the document (not upload date)"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("extracted_text", models.TextField(blank=True)),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Requires additional authorization to view",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_documents",
                        to="detection.patient",
                    ),
                ),
                (
                    "replaces",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaced_by",
                        to="medical_records.medicaldocument",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-document_date"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_name", models.CharField(max_length=200)),
                ("dosage", models.CharField(max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        help_text="e.g., 'Twice daily', '3x per day'", max_length=100
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        default="oral",
                        help_text="e.g., oral, injection, topical",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("current", "Currently Taking"),
                            ("discontinued", "Discontinued"),
                            ("completed", "Course Completed"),
                        ],
                        default="current",
                        max_length=20,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        help_text="Reason for taking medication", max_length=200
                    ),
                ),
                ("prescribing_doctor", models.CharField(blank=True, max_length=200)),
                ("side_effects", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="detection.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Surgery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surgery_name", models.CharField(max_length=200)),
                (
                    "procedure_code",
                    models.CharField(blank=True, help_text="CPT code", max_length=50),
                ),
                ("surgery_date", models.DateField()),
                ("surgeon_name", models.CharField(blank=True, max_length=200)),
                ("hospital", models.CharField(blank=True, max_length=200)),
                ("reason", models.TextField()),
                ("complications", models.TextField(blank=True)),
                ("outcome", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surgeries",
                        to="detection.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Surgeries",
                "ordering": ["-surgery_date"],
            },
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vaccine_name",
                    models.CharField(
                        choices=[
                            ("covid19_pfizer", "COVID-19 Pfizer-BioNTech"),
                            ("covid19_moderna", "COVID-19 Moderna"),
                            ("covid19_astrazeneca", "COVID-19 AstraZeneca"),
                            ("covid19_sinovac", "COVID-19 Sinovac"),
                            ("covid19_sinopharm", "COVID-19 Sinopharm"),
                            ("covid19_other", "COVID-19 Other"),
                            ("influenza", "Influenza"),
                            ("pneumococcal", "Pneumococcal"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("vaccine_brand", models.CharField(blank=True, max_length=100)),
                (
                    "dose_number",
                    models.IntegerField(help_text="Which dose (1st, 2nd, 3rd, etc.)"),
                ),
                ("lot_number", models.CharField(blank=True, max_length=100)),
                ("administered_date", models.DateField()),
                ("administered_by", models.CharField(blank=True, max_length=200)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Clinic/hospital name", max_length=200
                    ),
                ),
                ("side_effects", models.TextField(blank=True)),
                ("adverse_reaction", models.BooleanField(default=False)),
                (
                    "verification_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="medical_records/vaccination_certificates/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="detection.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-administered_date"],
            },
        ),
    ]
