# Generated by Django 5.2.8 on 2025-11-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="report",
            new_name="reporting_r_report__6633e1_idx",
            old_name="reporting_r_report__f9c8a0_idx",
        ),
        migrations.RenameIndex(
            model_name="report",
            new_name="reporting_r_patient_23b01d_idx",
            old_name="reporting_r_patient_8f3e3a_idx",
        ),
    ]
