# Generated by Django 5.2.8 on 2025-11-18 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("detection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(max_length=100, unique=True)),
                (
                    "retention_days",
                    models.IntegerField(help_text="Number of days to retain data"),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auto_delete",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically delete data after retention period",
                    ),
                ),
                (
                    "notify_before_days",
                    models.IntegerField(
                        default=30, help_text="Notify admins N days before deletion"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Data Retention Policies",
            },
        ),
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("hipaa_audit", "HIPAA Audit Report"),
                            ("gdpr_compliance", "GDPR Compliance Report"),
                            ("access_review", "Data Access Review"),
                            ("security_audit", "Security Audit"),
                            ("user_activity", "User Activity Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("summary", models.JSONField(help_text="Summary statistics")),
                ("details", models.JSONField(help_text="Detailed findings")),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="compliance_reports/%Y/%m/"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=150)),
                ("success", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("failure_reason", models.CharField(blank=True, max_length=200)),
                ("is_suspicious", models.BooleanField(default=False)),
                ("blocked", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["username", "-timestamp"],
                        name="audit_login_usernam_5f33e1_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="audit_login_ip_addr_e0f32f_idx",
                    ),
                    models.Index(
                        fields=["is_suspicious"], name="audit_login_is_susp_b1126e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=150)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("read", "Read/View"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Failed Login"),
                            ("export", "Data Export"),
                            ("report", "Report Generation"),
                            ("upload", "File Upload"),
                            ("download", "File Download"),
                            ("permission_change", "Permission Change"),
                            ("password_change", "Password Change"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_description", models.CharField(max_length=500)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, help_text="Previous state before change", null=True
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, help_text="New state after change", null=True
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True, help_text="Extra context data", null=True
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_audit_user_id_ea8c9f_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-timestamp"],
                        name="audit_audit_action__32de6f_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_audit_timesta_19e18a_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_audit_content_4c2ead_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accessor_role", models.CharField(max_length=20)),
                ("data_type", models.CharField(max_length=50)),
                ("data_id", models.PositiveIntegerField()),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("download", "Download"),
                            ("export", "Export"),
                            ("print", "Print"),
                            ("share", "Share"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "access_reason",
                    models.TextField(blank=True, help_text="Purpose of access"),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "is_legitimate",
                    models.BooleanField(
                        default=True,
                        help_text="Whether access was for legitimate medical purpose",
                    ),
                ),
                ("flagged_for_review", models.BooleanField(default=False)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "accessor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="detection.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-accessed_at"],
                        name="audit_dataa_patient_045af1_idx",
                    ),
                    models.Index(
                        fields=["accessor", "-accessed_at"],
                        name="audit_dataa_accesso_6cdb90_idx",
                    ),
                    models.Index(
                        fields=["flagged_for_review"],
                        name="audit_dataa_flagged_20602a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("change_reason", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-changed_at"],
                        name="audit_datac_content_8fc1ed_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("failed_login", "Multiple Failed Logins"),
                            ("unusual_access", "Unusual Data Access Pattern"),
                            ("bulk_export", "Bulk Data Export"),
                            ("privilege_escalation", "Privilege Escalation Attempt"),
                            ("after_hours", "After Hours Access"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "triggered_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("auto_blocked", models.BooleanField(default=False)),
                ("admin_notified", models.BooleanField(default=False)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
                "indexes": [
                    models.Index(
                        fields=["acknowledged", "-triggered_at"],
                        name="audit_secur_acknowl_174b09_idx",
                    ),
                    models.Index(
                        fields=["severity", "-triggered_at"],
                        name="audit_secur_severit_8b38b9_idx",
                    ),
                ],
            },
        ),
    ]
