# Generated by Django 4.2.7 on 2025-11-25 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='compliancereport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dataaccesslog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='datachange',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='securityalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_user_id_ea8c9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_action__32de6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_timesta_19e18a_idx',
        ),
        migrations.RemoveIndex(
            model_name='dataaccesslog',
            name='audit_dataa_patient_045af1_idx',
        ),
        migrations.RemoveIndex(
            model_name='dataaccesslog',
            name='audit_dataa_accesso_6cdb90_idx',
        ),
        migrations.RemoveIndex(
            model_name='datachange',
            name='audit_datac_content_8fc1ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginattempt',
            name='audit_login_usernam_5f33e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginattempt',
            name='audit_login_ip_addr_e0f32f_idx',
        ),
        migrations.RemoveIndex(
            model_name='securityalert',
            name='audit_secur_acknowl_174b09_idx',
        ),
        migrations.RemoveIndex(
            model_name='securityalert',
            name='audit_secur_severit_8b38b9_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='compliancereport',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='dataaccesslog',
            name='accessed_at',
        ),
        migrations.RemoveField(
            model_name='datachange',
            name='changed_at',
        ),
        migrations.RemoveField(
            model_name='loginattempt',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='securityalert',
            name='triggered_at',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AddField(
            model_name='datachange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datachange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='dataretentionpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='dataretentionpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', '-created_at'], name='audit_audit_action__4cc9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['patient', '-created_at'], name='audit_dataa_patient_f5fe95_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['accessor', '-created_at'], name='audit_dataa_accesso_7b038c_idx'),
        ),
        migrations.AddIndex(
            model_name='datachange',
            index=models.Index(fields=['content_type', 'object_id', '-created_at'], name='audit_datac_content_1ed811_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username', '-created_at'], name='audit_login_usernam_3f9d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', '-created_at'], name='audit_login_ip_addr_78572f_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['acknowledged', '-created_at'], name='audit_secur_acknowl_0dc957_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['severity', '-created_at'], name='audit_secur_severit_99c92d_idx'),
        ),
    ]
