# Generated by Django 4.2.7 on 2025-11-23 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('title', models.CharField(help_text='Announcement title (max 200 characters)', max_length=200)),
                ('message', models.TextField(help_text='Announcement message content')),
                ('priority', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('urgent', 'Urgent')], default='info', help_text='Priority level of the announcement', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this announcement is currently active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this announcement expires (optional)', null=True)),
                ('author', models.ForeignKey(help_text='User who created this announcement', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='announcemen_is_acti_b68c9c_idx'), models.Index(fields=['priority', '-created_at'], name='announcemen_priorit_0eb00b_idx')],
            },
        ),
    ]
