# Generated by Django 5.2.8 on 2025-11-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_populate_default_templates"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_a972ce_idx",
            old_name="notificatio_recipie_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_status_e1eb7a_idx",
            old_name="notificatio_status_idx",
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("prediction_ready", "Prediction Ready"),
                    ("critical_result", "Critical Result - COVID Positive"),
                    ("appointment_reminder", "Appointment Reminder"),
                    ("appointment_confirmed", "Appointment Confirmed"),
                    ("appointment_cancelled", "Appointment Cancelled"),
                    ("report_ready", "Report Ready"),
                    ("account_created", "Account Created"),
                    ("password_reset", "Password Reset"),
                    ("test_result_updated", "Test Result Updated"),
                    ("doctor_notes_added", "Doctor Notes Added"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
